### ISSUE TITLE
reanimated crash on this version of  expo / react-conf-app

### ISSUE THREAD

**Issue by yassine1982** [expo/react-conf-app#11] opened 2024-07-14 22:53 UTC
(NOBRIDGE) ERROR  ReanimatedError: [Reanimated] Tried to synchronously call a non-worklet function `t3` on the UI thread.
See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-synchronously-call-a-non-worklet-function-on-the-ui-thread for more details., js engine: reanimated
 (NOBRIDGE) ERROR  ReanimatedError: [Reanimated] Tried to synchronously call a non-worklet function `t4` on the UI thread.
See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-synchronously-call-a-non-worklet-function-on-the-ui-thread for more details., js engine: reanimated
 (NOBRIDGE) ERROR  ReanimatedError: [Reanimated] Tried to synchronously call a non-worklet function `t5` on the UI thread.

**Comment by kadikraman** [comment] 2024-07-22 18:13
Could you please provide steps to reproduce this?
- iOS or Android?
- real device or emulator/simulator
- did the error appear on launch or after an interaction?

**Comment by kadikraman** [comment] 2024-07-26 21:57
Closing due to a lack of a reproducible example. Please create a new issue with steps to reproduce if the problem persists.

**Closed by kadikraman** 2024-07-26 21:57 UTC
